apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "airflow.fullname" . }}-pdb
  labels:
    app: {{ template "airflow.name" . }}-scheduler
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "airflow.name" . }}-scheduler
      release: {{ .Release.Name }}
{{ toYaml .Values.airflow.podDisruptionBudget | indent 2 }}
