airflow:
  image:
     repository: airflow-docker-local
     tag: 0.1.1-13
  executor: Local
  service:
    type: LoadBalancer
  config:
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:airflow@airflow-postgresql:5432/airflow

    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__LOGGING_LEVEL: DEBUG
    AIRFLOW__CORE__FAB_LOGGING_LEVEL: WARN

    # AIRFLOW__CORE__LOGGING_CONFIG_CLASS:
    AIRFLOW__CORE__REMOTE_LOGGING: "False"
    # AIRFLOW__CORE__REMOVE_BASE_LOG_FOLDER: s3://
    # AIRFLOW__CORE__FERNET_KEY:
    # AIRFLOW__CORE__REMOTE_LOG_CONN_ID:
    # AIRFLOW__CORE__ENCRYPT_S3_LOGS: "True"
    AIRFLOW__HIVE__MAPRED_JOB_NAME_TEMPLATE: "Airflow HiveOperator task for {{hostname}}.{{dag_id}}.{{task_id}}.{{execution_date}}"
    # AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
    # AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.contrib.auth.backends.google_auth
    # AIRFLOW__WEBSERVER__RBAC: "True"
    AIRFLOW__WEBSERVER__NAVBAR_COLOR: "#123456"

    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: airflow-docker-local
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 0.1.1-13
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: airflow
    AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: airflow-env
    AIRFLOW__KUBERNETES__ENV_FROM_SECRET_REF: airflow-env
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: IfNotPresent
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
    # AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow

    # AIRFLOW__GOOGLE__CLIENT_ID:
    # AIRFLOW__GOOGLE__CLIENT_SECRET:
    # AIRFLOW__GOOGLE__OAUTH_CALLBACK_ROUTE: /oauth2callback
    # AIRFLOW__GOOGLE__DOMAIN: newmathdata.com



persistence:
  enabled: false
  existingClaim: ''

workers:
  enabled: false

postgresql:
  enabled: true

redis:
  enabled: false

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: false
